basePath: /api/v1
definitions:
  models.CreateKBRequest:
    properties:
      chunkSize:
        type: integer
      description:
        type: string
      name:
        type: string
    required:
    - name
    type: object
  models.KnowledgeBase:
    properties:
      chunkSize:
        type: integer
      createdAt:
        type: string
      description:
        type: string
      docCount:
        type: integer
      id:
        type: integer
      name:
        type: string
      status:
        type: string
      updatedAt:
        type: string
    type: object
  models.Response:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: 这是基于 Gin 和 OpenAPI 构建的 AI-KMS 后端服务。
  title: AI 知识库管理平台 API
  version: "1.0"
paths:
  /docs/{doc_id}:
    delete:
      description: 删除文档记录、关联的切片数据以及本地物理文件
      operationId: deleteDocument
      parameters:
      - description: 文档 ID
        in: path
        name: doc_id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
      summary: 删除文档
      tags:
      - Document
  /kb:
    get:
      consumes:
      - application/json
      description: 从数据库获取所有未被删除的知识库
      operationId: getKnowledgeBases
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/models.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/models.KnowledgeBase'
                  type: array
              type: object
      summary: 获取知识库列表
      tags:
      - KnowledgeBase
    post:
      consumes:
      - application/json
      description: 接收前端参数并在数据库中创建新记录
      operationId: creatKnowledgeBase
      parameters:
      - description: 请求参数
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/models.CreateKBRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/models.Response'
            - properties:
                data:
                  $ref: '#/definitions/models.KnowledgeBase'
              type: object
      summary: 创建新知识库
      tags:
      - KnowledgeBase
  /kb/{id}:
    delete:
      consumes:
      - application/json
      description: 根据 ID 软删除知识库记录
      operationId: deleteKnowledgeBase
      parameters:
      - description: 知识库 ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/models.Response'
      summary: 删除知识库
      tags:
      - KnowledgeBase
swagger: "2.0"
