basePath: /api/v1
definitions:
  controllers.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  controllers.RefreshRequest:
    properties:
      refresh_token:
        type: string
    required:
    - refresh_token
    type: object
  controllers.RegisterRequest:
    properties:
      password:
        example: "123456"
        type: string
      username:
        example: new_user
        type: string
    required:
    - password
    - username
    type: object
  controllers.UpdatePasswordRequest:
    properties:
      newPassword:
        example: "654321"
        type: string
      oldPassword:
        example: "123456"
        type: string
    required:
    - newPassword
    - oldPassword
    type: object
  controllers.UpdateUsernameRequest:
    properties:
      newUsername:
        example: super_admin
        type: string
    required:
    - newUsername
    type: object
  models.ChatRequest:
    properties:
      isContinue:
        description: 接收继续生成的信号和上下文
        type: boolean
      kbId:
        description: 接收前端传来的知识库 ID
        type: integer
      message:
        type: string
      partialContent:
        description: 已经生成的前半截内容
        type: string
      sessionId:
        type: integer
    required:
    - message
    type: object
  models.CreateKBRequest:
    properties:
      chunkSize:
        type: integer
      description:
        type: string
      name:
        type: string
      systemPrompt:
        description: 接收前端传来的提示词
        type: string
    required:
    - name
    type: object
  models.CreateSessionRequest:
    properties:
      kbId:
        type: integer
      title:
        type: string
    type: object
  models.DailyTokenStat:
    properties:
      cost:
        example: 0.256
        type: number
      date:
        example: "2020-01-01"
        type: string
      totalTokens:
        example: 1234
        type: integer
    type: object
  models.DashboardStatsData:
    properties:
      costTrend:
        items:
          $ref: '#/definitions/models.DailyTokenStat'
        type: array
      todayChats:
        example: 156
        type: integer
      totalDocs:
        type: integer
      totalUsers:
        example: 12
        type: integer
    type: object
  models.KnowledgeBase:
    properties:
      chunkSize:
        type: integer
      createdAt:
        type: string
      description:
        type: string
      docCount:
        type: integer
      id:
        type: integer
      name:
        type: string
      status:
        type: string
      systemPrompt:
        description: 系统提示词字段
        type: string
      updatedAt:
        type: string
      userId:
        type: integer
    type: object
  models.Response:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
    type: object
  models.SysConfig:
    type: object
  models.UpdateKBRequest:
    properties:
      description:
        example: 存放所有研发相关的基础文档
        type: string
      name:
        example: 研发需求库
        type: string
      systemPrompt:
        description: 允许用户修改提示词
        example: 你是一个专业的法务...
        type: string
    required:
    - name
    type: object
  models.UpdateSessionRequest:
    properties:
      isPinned:
        example: true
        type: boolean
      title:
        description: 使用指针类型 (*string, *bool)：区分前端是传了空值/false，还是根本没传。
        example: 新的会话标题
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: 这是基于 Gin 和 OpenAPI 构建的 AI-KMS 后端服务。
  title: AI 知识库管理平台 API
  version: "1.0"
paths:
  /chat:
    post:
      consumes:
      - application/json
      description: 采用 SSE (Server-Sent Events) 实现的流式打字机和思维链输出
      parameters:
      - description: 提问参数
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.ChatRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 返回 SSE 格式的数据流
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: 智能对话 (流式返回)
      tags:
      - 智能对话
  /configs:
    get:
      description: 获取系统大模型API Key等动态配置
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
      security:
      - BearerAuth: []
      summary: 获取所有系统配置项
      tags:
      - 系统配置
    put:
      description: 修改指定的系统配置项的值
      parameters:
      - description: 配置内容
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.SysConfig'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
      security:
      - BearerAuth: []
      summary: 更新单个系统配置
      tags:
      - 系统配置
  /configs/batch:
    post:
      consumes:
      - application/json
      parameters:
      - description: 配置列表
        in: body
        name: data
        required: true
        schema:
          items:
            $ref: '#/definitions/models.SysConfig'
          type: array
      responses: {}
      security:
      - BearerAuth: []
      summary: 批量更新系统配置
      tags:
      - 系统配置
  /dashboard:
    get:
      consumes:
      - application/json
      description: 统计系统的文档总数、用户总数、今日提问次数以及近7天的Token消耗与虚拟成本趋势
      produces:
      - application/json
      responses:
        "200":
          description: 获取成功
          schema:
            allOf:
            - $ref: '#/definitions/models.Response'
            - properties:
                data:
                  $ref: '#/definitions/models.DashboardStatsData'
              type: object
        "401":
          description: 未授权
          schema:
            $ref: '#/definitions/models.Response'
        "500":
          description: 系统内部错误
          schema:
            $ref: '#/definitions/models.Response'
      security:
      - BearerAuth: []
      summary: 获取系统数据大屏设计
      tags:
      - 数据看板 (Dashboard)
  /docs/{doc_id}:
    delete:
      description: 删除文档记录、关联的切片数据以及本地物理文件
      operationId: deleteDocument
      parameters:
      - description: 文档 ID
        in: path
        name: doc_id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
      summary: 删除文档
      tags:
      - Document
  /kb:
    get:
      consumes:
      - application/json
      description: 从数据库获取所有未被删除的知识库
      operationId: getKnowledgeBases
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/models.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/models.KnowledgeBase'
                  type: array
              type: object
      summary: 获取知识库列表
      tags:
      - KnowledgeBase
    post:
      consumes:
      - application/json
      description: 接收前端参数并在数据库中创建新记录
      operationId: creatKnowledgeBase
      parameters:
      - description: 创建知识库请求体
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.CreateKBRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/models.Response'
            - properties:
                data:
                  $ref: '#/definitions/models.KnowledgeBase'
              type: object
      summary: 创建新知识库
      tags:
      - KnowledgeBase
  /kb/{id}:
    delete:
      consumes:
      - application/json
      description: 根据 ID 软删除知识库记录
      operationId: deleteKnowledgeBase
      parameters:
      - description: 知识库 ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/models.Response'
      summary: 删除知识库
      tags:
      - KnowledgeBase
    put:
      consumes:
      - application/json
      description: 根据 ID 修改指定知识库的名称和描述
      parameters:
      - description: 知识库 ID
        in: path
        name: id
        required: true
        type: integer
      - description: 更新参数
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.UpdateKBRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 更新成功
          schema:
            $ref: '#/definitions/models.Response'
        "400":
          description: 参数错误，名称不能为空
          schema:
            $ref: '#/definitions/models.Response'
        "500":
          description: 更新失败
          schema:
            $ref: '#/definitions/models.Response'
      security:
      - BearerAuth: []
      summary: 更新知识库
      tags:
      - KnowledgeBase
  /login:
    post:
      consumes:
      - application/json
      description: 用户输入账号和密码进行登录，成功后返回短令牌 (accessToken) 和长令牌 (refreshToken)
      parameters:
      - description: 登录账号和密码
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/controllers.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/models.Response'
        "400":
          description: 参数错误
          schema:
            $ref: '#/definitions/models.Response'
        "401":
          description: 账号或密码错误
          schema:
            $ref: '#/definitions/models.Response'
      summary: 用户登录
      tags:
      - 认证 (Auth)
  /refresh:
    post:
      consumes:
      - application/json
      description: 使用长令牌换取新的短令牌
      parameters:
      - description: 刷新参数
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/controllers.RefreshRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/models.Response'
      summary: 刷新 Access Token
      tags:
      - 认证 (Auth)
  /register:
    post:
      consumes:
      - application/json
      description: 管理员在后台添加新用户
      parameters:
      - description: 注册参数
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/controllers.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/models.Response'
      summary: 注册新用户 (添加用户)
      tags:
      - 认证 (Auth)
  /sessions:
    get:
      consumes:
      - application/json
      description: 按时间降序获取历史会话
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/models.Response'
      summary: 获取会话列表
      tags:
      - 会话管理
    post:
      consumes:
      - application/json
      description: 创建一个新的空白聊天会话
      parameters:
      - description: 新建参数
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.CreateSessionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/models.Response'
      summary: 新建会话
      tags:
      - 会话管理
  /sessions/{id}:
    delete:
      consumes:
      - application/json
      description: 删除整个会话及其关联的所有消息
      parameters:
      - description: 会话ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/models.Response'
      summary: 删除会话
      tags:
      - 会话管理
    put:
      consumes:
      - application/json
      description: 支持局部更新会话的标题或置顶状态
      parameters:
      - description: 会话ID
        in: path
        name: id
        required: true
        type: integer
      - description: 更新参数
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.UpdateSessionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/models.Response'
      summary: 更新会话信息
      tags:
      - 会话管理
  /sessions/{id}/messages:
    get:
      consumes:
      - application/json
      description: 根据会话ID获取该会话下的所有聊天消息
      parameters:
      - description: 会话ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/models.Response'
      summary: 获取聊天记录
      tags:
      - 会话管理
  /user/avatar:
    delete:
      consumes:
      - application/json
      description: 将当前登录用户的头像字段清空为默认状态
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/models.Response'
      security:
      - BearerAuth: []
      summary: 移除当前用户头像
      tags:
      - 用户 (User)
    post:
      consumes:
      - multipart/form-data
      description: 接收前端传来的图片文件，保存到本地并更新数据库中的头像 URL
      parameters:
      - description: 头像图片文件
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/models.Response'
      security:
      - BearerAuth: []
      summary: 上传用户头像
      tags:
      - 用户 (User)
  /user/password:
    put:
      consumes:
      - application/json
      description: 验证旧密码并更新为新密码，更新后需要重新登录
      parameters:
      - description: 修改密码的参数
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/controllers.UpdatePasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/models.Response'
      security:
      - BearerAuth: []
      summary: 修改当前用户密码
      tags:
      - 用户 (User)
  /user/username:
    put:
      consumes:
      - application/json
      description: 修改用户名后，JWT 令牌会失效，前端需要强制重新登录
      parameters:
      - description: 修改用户名的参数
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/controllers.UpdateUsernameRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/models.Response'
      security:
      - BearerAuth: []
      summary: 修改当前用户名
      tags:
      - 用户 (User)
  /users:
    get:
      consumes:
      - application/json
      description: 在用户管理表格中展示所有用户
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/models.Response'
      security:
      - BearerAuth: []
      summary: 获取用户列表
      tags:
      - 用户 (User)
  /users/{id}:
    delete:
      consumes:
      - application/json
      description: 管理员在后台删除指定用户，超级管理员(admin)不能被删除
      parameters:
      - description: 要删除的用户ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/models.Response'
      security:
      - BearerAuth: []
      summary: 删除用户
      tags:
      - 用户 (User)
swagger: "2.0"
